name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - release/production

  pull_request:
    branches:
      - release/production

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0

        with:
          args: deploy --only hosting:tests
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
